export default [
    "do","you","ever","feel",
    // "like","a","plastic","bag","drifting","through","the","wind","wanting","to","start","again",
    // "do","you","ever","feel","feel","so","paper","thin","like","a","house","of","cards","one","blow","from","cavin'","in",
    // "do","you","ever","feel","already","buried","deep","six","feet","under","screams","but","no","one","seems","to","hear",
    // "a","thing","do","you","know","that","there's","still","a","chance","for","you","'cause","there's","a","spark","in","you",
    // "you","just","gotta","ignite","the","light","and","let","it","shine","just","own","the","night","like","the","fourth","of",
    // "july","'cause","baby","you're","a","firework","come","on","show","'em","what","you're","worth","make","'em","go","awe",
    // "awe","awe","as","you","shoot","across","the","sky","baby","you're","a","firework","come","on","let","your","colors",
    // "burst","make","'em","go","awe","awe","awe","you're","gonna","leave","'em","all","in","awe","awe","awe","you","don't",
    // "have","to","feel","like","a","waste","of","space","you're","original","cannot","be","replaced","if","you","only","knew",
    // "what","the","future","holds","after","a","hurricane","comes","a","rainbow","maybe","a","reason","why","all","the","doors",
    // "are","closed","so","you","could","open","one","that","leads","you","to","the","perfect","road","like","a","lightning",
    // "bolt","your","heart","will","glow","and","when","it's","time","you'll","know","you","just","gotta","ignite","the","light",
    // "and","let","it","shine","just","own","the","night","like","the","fourth","of","july","'cause","baby","you're","a","firework",
    // "come","on","show","'em","what","you're","worth","make","'em","go","awe","awe","awe","as","you","shoot","across","the",
    // "sky","baby","you're","a","firework","come","on","let","your","colors","burst","make","'em","go","awe","awe","awe",
    // "you're","gonna","leave","'em","all","in","awe","awe","awe","boom","boom","boom","even","brighter","than","the","moon","moon",
    // "moon","it's","always","been","inside","of","you","you","you","and","now","it's","time","to","let","it","through","'cause",
    // "baby","you're","a","firework","come","on","show","'em","what","you're","worth","make","'em","go","awe","awe","awe","as",
    // "you","shoot","across","the","sky","baby","you're","a","firework","come","on","let","your","colors","burst","make",
    // "'em","go","awe","awe","awe","you're","gonna","leave","'em","all","in","awe","awe","awe","boom","boom","boom","even",
    // "brighter","than","the","moon","moon","moon","boom","boom","boom","even","brighter","than","the","moon","moon","moon"
];  